package com.playjoy.enums;

public enum Category {
    ALL,
    DISCOUNT,
    NAME_PUZZLE,
    BUSY_BOARDS,
    NEW_BUSY_BOARDS_XXL,
    NEW_BUSY_BOARD_PARTS_DIY,
    FIRST_DAY_OF_SCHOOL_SIGN,
    NEW_WOODEN_CARS,
    WOODEN_TRAINS,
    NIGHT_LIGHTS,
    NEW_PERSONALIZED_APRONS,
    NEW_BIRTHDAY_CROWNS,
    NAME_BLANKETS_AND_BASKETS,
    THEMATIC_NAME_PUZZLE,
    MILITARY_TOYS,
    MONTESSORI_TOYS,
    EDUCATIONAL_TOYS,
    NURSERY_DECOR,
    ADVENT_CALENDAR,
    CHRISTMAS_DECOR,
    EASTER_DECOR,
    WITHOUT_NUMBERS
}
